# Generated by Django 5.2.1 on 2025-05-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_device_id_alter_device_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
