# Generated by Django 5.2.1 on 2025-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional unique device ID from ESP32', max_length=100, null=True, unique=True),
        ),
    ]
