# Generated by Django 5.2.1 on 2025-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_notification_options_notification_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='registration_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('wifi', 'WiFi')], default='manual', max_length=20),
        ),
    ]
