# Generated by Django 5.2.1 on 2025-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_metadata_device_registration_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('critical', 'Critical'), ('tamper', 'Tamper Alert'), ('low', 'Low Level'), ('medium', 'Medium Level'), ('high', 'High Level'), ('success', 'Success'), ('offline', 'Offline'), ('info', 'Information')], default='info', help_text='Type of alert for frontend styling', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=50, help_text='Priority for sorting (100=critical, 1=lowest)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='alert',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tamper',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
